name: build dev

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cimg/android:2021.09.1-ndk
      options: --user root
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: android

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Install yarn
      run: npm install -g yarn
    
    - name: Load Cache
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'
    
    - name: Install packages
      run: yarn install --frozen-lockfile  # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)

    - name: Sync purge and compile lingui.js locales
      run: |
        sed "s/<TRANSLATION_IO_APIKEY>/$TRANSLATION_IO_APIKEY/" lingui.config.js.example > lingui.config.js;
        yarn sync_and_purge;
      env:
        TRANSLATION_IO_APIKEY: ${{ secrets.TRANSLATION_IO_APIKEY }}

    - name: Make Gradlew Executable
      run: cd android && chmod +x ./gradlew

    - name: build
      run: |
        cd android && ./gradlew --no-daemon build -PnoDebug;

    - name: Sign App Bundle
      id: sign_app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: android/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
        alias: ${{ secrets.ANDROID_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: android/app/build/outputs/apk/release/app-release.apk
