name: build dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+-rc\d+'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cimg/android:2022.06.1
      options: --user root
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: dev

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Install yarn
      run: npm install -g yarn

    - name: Load Cache
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'
    
    - name: Install packages
      run: yarn install

    - name: Sync purge and compile lingui.js locales
      run: |
        sed "s/<TRANSLATION_IO_APIKEY>/$TRANSLATION_IO_APIKEY/" lingui.config.js.example > lingui.config.js;
        yarn sync_and_purge;
      env:
        TRANSLATION_IO_APIKEY: ${{ secrets.TRANSLATION_IO_APIKEY }}

    - name: build
      run: |
        cd android;
        ./gradlew build -x lint -x test -x bundleDebugJsAndAssets -x copyDebugBundledJs -x assembleAndroidTest -x compileDebugSources;
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: android/app/build/outputs/apk/release/app-release.apk
