name: test build

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: cimg/android:2022.06.1
      options: --user root
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
        ref: dev

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    
    - name: install packages
      run: yarn install

    - name: test build
      run: |
        npx react-native webpack-bundle --platform android --dev false --entry-file index.tsx --bundle-output build/android/index.android.bundle --assets-dest build/android;
        cd android;
        ./gradlew --no-daemon assembleRelease -x bundleReleaseJsAndAssets;
