name: test build

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: cimg/android:2022.06.1
      options: --user root
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: dev

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Install yarn
      run: npm install -g yarn

    - name: Load Cache
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'
    
    - name: Install packages
      run: yarn install

    - name: Test build
      run: |
        cd android;
        ./gradlew build -x lint -x test -x bundleDebugJsAndAssets -x copyDebugBundledJs -x assembleAndroidTest -x compileDebugSources;
